server:
  port: 3001

  spring:
    # ??? ??
    profiles:
      active: dev

spring:
  # ??? ??? ?? ??
  datasource:
    driverClassName: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: DONKEY
    password: _aA123456
  aop:
    proxy-target-class: true
  # JPA ??
  jpa:
    open-in-view: false
    properties:
      hibernate:
        # ???? ?? ?? ??
        show_sql: true
        # ?? ?? ???? ??? ??? ?? ???
        format_sql: true
        use_sql_comments: true
        defer-datasource-initialization: true
        # dialect: org.hibernate.dialect.OracleDialect
    hibernate:
      ddlAuto: update

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

# JSON WebToken ??
jwt:
  header: Authorization
  secret: YWJjZGVmZ2hpamtsbW5vcHFyc3R1dnd6eXoxMjMxMjMxMjMxMjMxMjMxMzEyMzEyMzEzMTIzMTIzMTIzMTMxMjMxMzEzMTMxMjM #base64 ??? a-z
  accessTokenValidityInSeconds: 3600 # 60 min
